REALMS = {
    "Aegwynn": ["EU", "US"],
    "Aerie Peak": ["EU", "US"],
    "Agamaggan": ["EU", "US"],
    "Aggra (Português)": ["EU"],
    "Aggramar": ["EU", "US"],
    "Ahn'Qiraj": ["EU"],
    "Akama": ["US"],
    "Al'Akir": ["EU"],
    "Alexstrasza": ["EU", "US", "KR"],
    "Alleria": ["EU", "US"],
    "Alonsus": ["EU"],
    "Altar of Storms": ["US"],
    "Alterac Mountains": ["US"],
    "Aman'Thul": ["EU", "US"],
    "Ambossar": ["EU"],
    "Anachronos": ["EU"],
    "Andorhal": ["US"],
    "Anetheron": ["EU", "US"],
    "Antonidas": ["EU", "US"],
    "Anub'arak": ["EU", "US"],
    "Anvilmar": ["US"],
    "Arak-arahm": ["EU"],
    "Arathi": ["EU"],
    "Arathor": ["EU", "US"],
    "Archimonde": ["EU", "US"],
    "Area 52": ["EU", "US"],
    "Argent Dawn": ["EU", "US"],
    "Arthas": ["EU", "US", "TW"],
    "Arygos": ["EU", "US", "TW"],
    "Ashenvale": ["EU"],
    "Aszune": ["EU"],
    "Auchindoun": ["EU", "US"],
    "Azgalor": ["US"],
    "Azjol-Nerub": ["EU", "US"],
    "Azralon": ["US"],
    "Azshara": ["EU", "US", "KR"],
    "Azuregos": ["EU"],
    "Azuremyst": ["EU", "US"],
    "Baelgun": ["EU", "US"],
    "Balnazzar": ["EU", "US"],
    "Barthilas": ["US"],
    "Black Dragonflight": ["US"],
    "Blackhand": ["EU", "US"],
    "Blackmoore": ["EU"],
    "Blackrock": ["EU", "US"],
    "Blackscar": ["EU"],
    "Blackwater Raiders": ["US"],
    "Blackwing Lair": ["US"],
    "Blade's Edge": ["EU", "US"],
    "Bladefist": ["EU", "US"],
    "Bleeding Hollow": ["US", "TW"],
    "Blood Furnace": ["US"],
    "Bloodfeather": ["EU"],
    "Bloodhoof": ["EU", "US"],
    "Bloodscalp": ["EU", "US"],
    "Blutkessel": ["EU"],
    "Bonechewer": ["US"],
    "Booty Bay": ["EU"],
    "Borean Tundra": ["EU", "US"],
    "Boulderfist": ["EU", "US"],
    "Bronze Dragonflight": ["EU"],
    "Bronzebeard": ["EU", "US"],
    "Burning Blade": ["EU", "US"],
    "Burning Legion": ["EU", "US", "KR"],
    "Burning Steppes": ["EU"],
    "C'Thun": ["EU"],
    "Caelestrasz": ["US"],
    "Cairne": ["US"],
    "Cenarion Circle": ["US"],
    "Cenarius": ["US", "KR"],
    "Chamber of Aspects": ["EU"],
    "Chants éternels": ["EU"],
    "Chillwind Point": ["TW"],
    "Cho'gall": ["EU", "US"],
    "Chromaggus": ["EU", "US"],
    "Coilfang": ["US"],
    "Colinas Pardas": ["EU"],
    "Confrérie du Thorium": ["EU"],
    "Conseil des Ombres": ["EU"],
    "Crushridge": ["EU", "US"],
    "Crystalpine Stinger": ["TW"],
    "Culte de la Rive noire": ["EU"],
    "Daggerspine": ["EU", "US"],
    "Dalaran": ["EU", "US", "KR"],
    "Dalvengyr": ["EU", "US"],
    "Dark Iron": ["US"],
    "Darkmoon Faire": ["EU"],
    "Darksorrow": ["EU"],
    "Darkspear": ["EU", "US"],
    "Darrowmere": ["US"],
    "Das Konsortium": ["EU"],
    "Das Syndikat": ["EU"],
    "Dath'Remar": ["US"],
    "Dawnbringer": ["US"],
    "Deathguard": ["EU"],
    "Deathweaver": ["EU"],
    "Deathwing": ["EU", "US", "KR"],
    "Deepholm": ["EU"],
    "Defias Brotherhood": ["EU"],
    "Demon Fall Canyon": ["TW"],
    "Demon Soul": ["US"],
    "Dentarg": ["EU", "US"],
    "Der Mithrilorden": ["EU"],
    "Der Rat von Dalaran": ["EU"],
    "Der abyssische Rat": ["EU"],
    "Destromath": ["EU", "US"],
    "Dethecus": ["EU", "US"],
    "Detheroc": ["US"],
    "Die Aldor": ["EU"],
    "Die Arguswacht": ["EU"],
    "Die Nachtwache": ["EU"],
    "Die Silberne Hand": ["EU"],
    "Die Todeskrallen": ["EU"],
    "Die ewige Wacht": ["EU"],
    "Doomhammer": ["EU", "US"],
    "Draenor": ["EU", "US"],
    "Dragonblight": ["EU", "US"],
    "Dragonmaw": ["EU", "US", "TW"],
    "Drak'Tharon": ["US"],
    "Drak'thul": ["EU", "US"],
    "Draka": ["US"],
    "Drakkari": ["US"],
    "Dreadmaul": ["US"],
    "Drek'Thar": ["EU"],
    "Drenden": ["US"],
    "Dun Modr": ["EU"],
    "Dun Morogh": ["EU"],
    "Dunemaul": ["EU", "US"],
    "Durotan": ["EU", "US", "KR"],
    "Duskwood": ["US"],
    "Earthen Ring": ["EU", "US"],
    "Echo Isles": ["US"],
    "Echsenkessel": ["EU"],
    "Eitrigg": ["EU", "US"],
    "Eldre'Thalas": ["EU", "US"],
    "Elune": ["EU", "US"],
    "Emerald Dream": ["EU", "US"],
    "Emeriss": ["EU"],
    "Eonar": ["EU", "US"],
    "Eredar": ["EU", "US"],
    "Eversong": ["EU"],
    "Executus": ["EU", "US"],
    "Exodar": ["EU", "US"],
    "Farstriders": ["US"],
    "Feathermoon": ["US"],
    "Fenris": ["US"],
    "Festung der Stürme": ["EU"],
    "Firetree": ["US"],
    "Fizzcrank": ["US"],
    "Fordragon": ["EU"],
    "Forscherliga": ["EU"],
    "Frostmane": ["EU", "US", "TW"],
    "Frostmourne": ["EU", "US"],
    "Frostwhisper": ["EU"],
    "Frostwolf": ["EU", "US"],
    "Galakrond": ["EU", "US"],
    "Gallywix": ["US"],
    "Garithos": ["US"],
    "Garona": ["EU", "US", "KR"],
    "Garrosh": ["EU", "US"],
    "Genjuros": ["EU"],
    "Ghostlands": ["EU", "US"],
    "Gilneas": ["EU", "US"],
    "Gnomeregan": ["US"],
    "Goldrinn": ["EU", "US"],
    "Gordunni": ["EU"],
    "Gorefiend": ["US"],
    "Gorgonnash": ["EU", "US"],
    "Greymane": ["EU", "US"],
    "Grim Batol": ["EU"],
    "Grizzly Hills": ["US"],
    "Grom": ["EU"],
    "Gul'dan": ["EU", "US", "KR"],
    "Gundrak": ["US"],
    "Gurubashi": ["US"],
    "Hakkar": ["EU", "US"],
    "Haomarush": ["EU", "US"],
    "Hellfire": ["EU"],
    "Hellscream": ["EU", "US", "TW", "KR"],
    "Howling Fjord": ["EU"],
    "Hydraxis": ["US"],
    "Hyjal": ["EU", "US", "KR"],
    "Icecrown": ["US", "TW"],
    "Illidan": ["EU", "US"],
    "Jaedenar": ["EU", "US"],
    "Jubei'Thos": ["US"],
    "Kael'thas": ["EU", "US"],
    "Kalecgos": ["US"],
    "Karazhan": ["EU"],
    "Kargath": ["EU", "US"],
    "Kazzak": ["EU"],
    "Kel'Thuzad": ["EU", "US"],
    "Khadgar": ["EU", "US"],
    "Khaz Modan": ["EU", "US"],
    "Khaz'goroth": ["EU", "US"],
    "Kil'jaeden": ["EU", "US"],
    "Kilrogg": ["EU", "US"],
    "Kirin Tor": ["EU", "US"],
    "Kor'gall": ["EU"],
    "Korgath": ["US"],
    "Korialstrasz": ["US"],
    "Krag'jin": ["EU"],
    "Krasus": ["EU"],
    "Krol Blade": ["TW"],
    "Kul Tiras": ["EU", "US"],
    "Kult der Verdammten": ["EU"],
    "La Croisade écarlate": ["EU"],
    "Laughing Skull": ["EU", "US"],
    "Les Clairvoyants": ["EU"],
    "Les Sentinelles": ["EU"],
    "Lethon": ["US"],
    "Lich King": ["EU"],
    "Light's Hope": ["TW"],
    "Lightbringer": ["EU", "US"],
    "Lightning's Blade": ["EU", "US"],
    "Lightninghoof": ["US"],
    "Llane": ["US"],
    "Lordaeron": ["EU"],
    "Los Errantes": ["EU"],
    "Lothar": ["EU", "US"],
    "Madmortem": ["EU"],
    "Madoran": ["US"],
    "Maelstrom": ["US"],
    "Magtheridon": ["EU", "US"],
    "Maiev": ["US"],
    "Mal'Ganis": ["EU", "US"],
    "Malfurion": ["EU", "US", "KR"],
    "Malorne": ["EU", "US"],
    "Malygos": ["EU", "US"],
    "Mannoroth": ["EU", "US"],
    "Marécage de Zangar": ["EU"],
    "Mazrigos": ["EU"],
    "Medivh": ["EU", "US"],
    "Menethil": ["TW"],
    "Minahonda": ["EU"],
    "Misha": ["US"],
    "Mok'Nathal": ["US"],
    "Moon Guard": ["US"],
    "Moonglade": ["EU"],
    "Moonrunner": ["US"],
    "Mug'thol": ["EU", "US"],
    "Muradin": ["US"],
    "Nagrand": ["EU", "US"],
    "Nathrezim": ["EU", "US"],
    "Naxxramas": ["EU"],
    "Nazgrel": ["US"],
    "Nazjatar": ["EU", "US"],
    "Nefarian": ["EU"],
    "Nemesis": ["EU", "US"],
    "Neptulon": ["EU"],
    "Ner'zhul": ["EU", "US"],
    "Nera'thor": ["EU"],
    "Nesingwary": ["US"],
    "Nethersturm": ["EU"],
    "Nightsong": ["TW"],
    "Nordrassil": ["EU", "US"],
    "Norgannon": ["EU", "US", "KR"],
    "Nozdormu": ["EU"],
    "Onyxia": ["EU", "US"],
    "Order of the Cloud Serpent": ["TW"],
    "Outland": ["EU"],
    "Perenolde": ["EU", "US"],
    "Pozzo dell'Eternità": ["EU"],
    "Proudmoore": ["EU", "US"],
    "Quel'Thalas": ["EU", "US"],
    "Quel'dorei": ["US", "TW"],
    "Ragnaros": ["EU", "US"],
    "Rajaxx": ["EU"],
    "Rashgarroth": ["EU"],
    "Ravencrest": ["EU", "US"],
    "Ravenholdt": ["EU", "US"],
    "Razuvious": ["EU"],
    "Rexxar": ["EU", "US", "KR"],
    "Rivendare": ["US"],
    "Runetotem": ["EU", "US"],
    "Sanguino": ["EU"],
    "Sargeras": ["EU", "US"],
    "Saurfang": ["EU", "US"],
    "Scarlet Crusade": ["US"],
    "Scarshield Legion": ["EU"],
    "Scilla": ["US"],
    "Sen'jin": ["EU", "US"],
    "Sentinels": ["US"],
    "Shadow Council": ["US"],
    "Shadowmoon": ["US", "TW"],
    "Shadowsong": ["EU", "US"],
    "Shandris": ["US"],
    "Shattered Halls": ["EU", "US"],
    "Shattered Hand": ["EU", "US"],
    "Shattrath": ["EU"],
    "Shen'dralar": ["EU"],
    "Shu'halo": ["US"],
    "Silver Hand": ["US"],
    "Silvermoon": ["EU", "US"],
    "Silverwing Hold": ["TW"],
    "Sinstralis": ["EU"],
    "Sisters of Elune": ["US"],
    "Skullcrusher": ["EU", "US"],
    "Skywall": ["US", "TW"],
    "Smolderthorn": ["US"],
    "Soulflayer": ["EU"],
    "Spinebreaker": ["EU", "US"],
    "Spirestone": ["US", "TW"],
    "Sporeggar": ["EU"],
    "Staghelm": ["US"],
    "Steamwheedle Cartel": ["EU", "US"],
    "Stonemaul": ["US"],
    "Stormrage": ["EU", "US", "KR"],
    "Stormreaver": ["EU", "US"],
    "Stormscale": ["EU", "US", "TW"],
    "Sundown Marsh": ["TW"],
    "Sunstrider": ["EU"],
    "Suramar": ["EU", "US"],
    "Sylvanas": ["EU"],
    "Taerar": ["EU"],
    "Talnivarr": ["EU"],
    "Tanaris": ["US"],
    "Tarren Mill": ["EU"],
    "Teldrassil": ["EU"],
    "Temple noir": ["EU"],
    "Terenas": ["EU", "US"],
    "Terokkar": ["EU", "US"],
    "Terrordar": ["EU"],
    "Thaurissan": ["US"],
    "The Forgotten Coast": ["US"],
    "The Maelstrom": ["EU"],
    "The Scryers": ["US"],
    "The Sha'tar": ["EU"],
    "The Underbog": ["US"],
    "The Venture Co": ["EU", "US"],
    "Theradras": ["EU"],
    "Thermaplugg": ["EU"],
    "Thorium Brotherhood": ["US"],
    "Thrall": ["EU", "US"],
    "Throk'Feroth": ["EU"],
    "Thunderhorn": ["EU", "US"],
    "Thunderlord": ["US"],
    "Tichondrius": ["EU", "US"],
    "Tirion": ["EU"],
    "Todeswache": ["EU"],
    "Tol Barad": ["US"],
    "Tortheldrin": ["US"],
    "Trollbane": ["EU", "US"],
    "Turalyon": ["EU", "US"],
    "Twilight's Hammer": ["EU"],
    "Twisting Nether": ["EU", "US"],
    "Tyrande": ["EU"],
    "Uldaman": ["EU", "US"],
    "Ulduar": ["EU"],
    "Uldum": ["EU", "US"],
    "Un'Goro": ["EU"],
    "Undermine": ["US"],
    "Ursin": ["US"],
    "Uther": ["US"],
    "Varimathras": ["EU"],
    "Vashj": ["EU", "US"],
    "Vek'lor": ["EU"],
    "Vek'nilash": ["EU", "US"],
    "Velen": ["US"],
    "Vol'jin": ["EU"],
    "Warsong": ["US"],
    "Whisperwind": ["US", "TW"],
    "Wildhammer": ["EU", "US", "KR"],
    "Windrunner": ["US", "KR"],
    "Winterhoof": ["US"],
    "World Tree": ["TW"],
    "Wrathbringer": ["EU", "TW"],
    "Wyrmrest Accord": ["US"],
    "Xavius": ["EU"],
    "Ysera": ["EU", "US"],
    "Ysondre": ["EU", "US"],
    "Zangarmarsh": ["US"],
    "Zealot Blade": ["TW"],
    "Zenedar": ["EU"],
    "Zirkel des Cenarius": ["EU"],
    "Zul'jin": ["EU", "US", "KR"],
    "Zuluhed": ["EU", "US"],
}

REGIONS = [
    "EU",
    "US",
    "KR",
    "TW",
    # "CN", # RIP
]
