REALMS = [
    "Aegwynn",
    "Aerie Peak",
    "Agamaggan",
    "Aggra (Português)",
    "Aggramar",
    "Ahn'Qiraj",
    "Akama",
    "Al'Akir",
    "Alexstrasza",
    "Alleria",
    "Alonsus",
    "Altar of Storms",
    "Alterac Mountains",
    "Aman'Thul",
    "Ambossar",
    "Anachronos",
    "Andorhal",
    "Anetheron",
    "Antonidas",
    "Anub'arak",
    "Anvilmar",
    "Arak-arahm",
    "Arathi",
    "Arathor",
    "Archimonde",
    "Area 52",
    "Argent Dawn",
    "Arthas",
    "Arygos",
    "Ashenvale",
    "Aszune",
    "Auchindoun",
    "Azgalor",
    "Azjol-Nerub",
    "Azralon",
    "Azshara",
    "Azuregos",
    "Azuremyst",
    "Baelgun",
    "Balnazzar",
    "Barthilas",
    "Black Dragonflight",
    "Blackhand",
    "Blackmoore",
    "Blackrock",
    "Blackscar",
    "Blackwater Raiders",
    "Blackwing Lair",
    "Blade's Edge",
    "Bladefist",
    "Bleeding Hollow",
    "Blood Furnace",
    "Bloodfeather",
    "Bloodhoof",
    "Bloodscalp",
    "Blutkessel",
    "Bonechewer",
    "Booty Bay",
    "Borean Tundra",
    "Boulderfist",
    "Bronze Dragonflight",
    "Bronzebeard",
    "Burning Blade",
    "Burning Legion",
    "Burning Steppes",
    "C'Thun",
    "Caelestrasz",
    "Cairne",
    "Cenarion Circle",
    "Cenarius",
    "Chamber of Aspects",
    "Chants éternels",
    "Chillwind Point",
    "Cho'gall",
    "Chromaggus",
    "Coilfang",
    "Colinas Pardas",
    "Confrérie du Thorium",
    "Conseil des Ombres",
    "Crushridge",
    "Crystalpine Stinger",
    "Culte de la Rive noire",
    "Daggerspine",
    "Dalaran",
    "Dalvengyr",
    "Dark Iron",
    "Darkmoon Faire",
    "Darksorrow",
    "Darkspear",
    "Darrowmere",
    "Das Konsortium",
    "Das Syndikat",
    "Dath'Remar",
    "Dawnbringer",
    "Deathguard",
    "Deathweaver",
    "Deathwing",
    "Deepholm",
    "Defias Brotherhood",
    "Demon Fall Canyon",
    "Demon Soul",
    "Dentarg",
    "Der Mithrilorden",
    "Der Rat von Dalaran",
    "Der abyssische Rat",
    "Destromath",
    "Dethecus",
    "Detheroc",
    "Die Aldor",
    "Die Arguswacht",
    "Die Nachtwache",
    "Die Silberne Hand",
    "Die Todeskrallen",
    "Die ewige Wacht",
    "Doomhammer",
    "Draenor",
    "Dragonblight",
    "Dragonmaw",
    "Drak'Tharon",
    "Drak'thul",
    "Draka",
    "Drakkari",
    "Dreadmaul",
    "Drek'Thar",
    "Drenden",
    "Dun Modr",
    "Dun Morogh",
    "Dunemaul",
    "Durotan",
    "Duskwood",
    "Earthen Ring",
    "Echo Isles",
    "Echsenkessel",
    "Eitrigg",
    "Eldre'Thalas",
    "Elune",
    "Emerald Dream",
    "Emeriss",
    "Eonar",
    "Eredar",
    "Eversong",
    "Executus",
    "Exodar",
    "Farstriders",
    "Feathermoon",
    "Fenris",
    "Festung der Stürme",
    "Firetree",
    "Fizzcrank",
    "Fordragon",
    "Forscherliga",
    "Frostmane",
    "Frostmourne",
    "Frostwhisper",
    "Frostwolf",
    "Galakrond",
    "Gallywix",
    "Garithos",
    "Garona",
    "Garrosh",
    "Genjuros",
    "Ghostlands",
    "Gilneas",
    "Gnomeregan",
    "Goldrinn",
    "Gordunni",
    "Gorefiend",
    "Gorgonnash",
    "Greymane",
    "Grim Batol",
    "Grizzly Hills",
    "Grom",
    "Gul'dan",
    "Gundrak",
    "Gurubashi",
    "Hakkar",
    "Haomarush",
    "Hellfire",
    "Hellscream",
    "Howling Fjord",
    "Hydraxis",
    "Hyjal",
    "Icecrown",
    "Illidan",
    "Jaedenar",
    "Jubei'Thos",
    "Kael'thas",
    "Kalecgos",
    "Karazhan",
    "Kargath",
    "Kazzak",
    "Kel'Thuzad",
    "Khadgar",
    "Khaz Modan",
    "Khaz'goroth",
    "Kil'jaeden",
    "Kilrogg",
    "Kirin Tor",
    "Kor'gall",
    "Korgath",
    "Korialstrasz",
    "Krag'jin",
    "Krasus",
    "Krol Blade",
    "Kul Tiras",
    "Kult der Verdammten",
    "La Croisade écarlate",
    "Laughing Skull",
    "Les Clairvoyants",
    "Les Sentinelles",
    "Lethon",
    "Lich King",
    "Light's Hope",
    "Lightbringer",
    "Lightning's Blade",
    "Lightninghoof",
    "Llane",
    "Lordaeron",
    "Los Errantes",
    "Lothar",
    "Madmortem",
    "Madoran",
    "Maelstrom",
    "Magtheridon",
    "Maiev",
    "Mal'Ganis",
    "Malfurion",
    "Malorne",
    "Malygos",
    "Mannoroth",
    "Marécage de Zangar",
    "Mazrigos",
    "Medivh",
    "Menethil",
    "Minahonda",
    "Misha",
    "Mok'Nathal",
    "Moon Guard",
    "Moonglade",
    "Moonrunner",
    "Mug'thol",
    "Muradin",
    "Nagrand",
    "Nathrezim",
    "Naxxramas",
    "Nazgrel",
    "Nazjatar",
    "Nefarian",
    "Nemesis",
    "Neptulon",
    "Ner'zhul",
    "Nera'thor",
    "Nesingwary",
    "Nethersturm",
    "Nightsong",
    "Nordrassil",
    "Norgannon",
    "Nozdormu",
    "Onyxia",
    "Order of the Cloud Serpent",
    "Outland",
    "Perenolde",
    "Pozzo dell'Eternità",
    "Proudmoore",
    "Quel'Thalas",
    "Quel'dorei",
    "Ragnaros",
    "Rajaxx",
    "Rashgarroth",
    "Ravencrest",
    "Ravenholdt",
    "Razuvious",
    "Rexxar",
    "Rivendare",
    "Runetotem",
    "Sanguino",
    "Sargeras",
    "Saurfang",
    "Scarlet Crusade",
    "Scarshield Legion",
    "Scilla",
    "Sen'jin",
    "Sentinels",
    "Shadow Council",
    "Shadowmoon",
    "Shadowsong",
    "Shandris",
    "Shattered Halls",
    "Shattered Hand",
    "Shattrath",
    "Shen'dralar",
    "Shu'halo",
    "Silver Hand",
    "Silvermoon",
    "Silverwing Hold",
    "Sinstralis",
    "Sisters of Elune",
    "Skullcrusher",
    "Skywall",
    "Smolderthorn",
    "Soulflayer",
    "Spinebreaker",
    "Spirestone",
    "Sporeggar",
    "Staghelm",
    "Steamwheedle Cartel",
    "Stonemaul",
    "Stormrage",
    "Stormreaver",
    "Stormscale",
    "Sundown Marsh",
    "Sunstrider",
    "Suramar",
    "Sylvanas",
    "Taerar",
    "Talnivarr",
    "Tanaris",
    "Tarren Mill",
    "Teldrassil",
    "Temple noir",
    "Terenas",
    "Terokkar",
    "Terrordar",
    "Thaurissan",
    "The Forgotten Coast",
    "The Maelstrom",
    "The Scryers",
    "The Sha'tar",
    "The Underbog",
    "The Venture Co",
    "Theradras",
    "Thermaplugg",
    "Thorium Brotherhood",
    "Thrall",
    "Throk'Feroth",
    "Thunderhorn",
    "Thunderlord",
    "Tichondrius",
    "Tirion",
    "Todeswache",
    "Tol Barad",
    "Tortheldrin",
    "Trollbane",
    "Turalyon",
    "Twilight's Hammer",
    "Twisting Nether",
    "Tyrande",
    "Uldaman",
    "Ulduar",
    "Uldum",
    "Un'Goro",
    "Undermine",
    "Ursin",
    "Uther",
    "Varimathras",
    "Vashj",
    "Vek'lor",
    "Vek'nilash",
    "Velen",
    "Vol'jin",
    "Warsong",
    "Whisperwind",
    "Wildhammer",
    "Windrunner",
    "Winterhoof",
    "World Tree",
    "Wrathbringer",
    "Wyrmrest Accord",
    "Xavius",
    "Ysera",
    "Ysondre",
    "Zangarmarsh",
    "Zealot Blade",
    "Zenedar",
    "Zirkel des Cenarius",
    "Zul'jin",
    "Zuluhed",
]
